# Generated by Django 2.2.5 on 2019-09-22 18:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=30)),
                ('votes', models.IntegerField(default=0)),
                ('question_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollsapp.Questions')),
            ],
        ),
    ]
