# Generated by Django 2.2.5 on 2019-09-22 18:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('pollsapp', '0002_auto_20190922_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
